compiler:
  evm_version: berlin
  solc:
    version: 0.7.6
    optimizer:
      enabled: true
      runs: 200
    remappings:
      - "@balancer-labs=node_modules/@balancer-labs"
      - "@openzeppelin=node_modules/@openzeppelin"

networks:
  development:
    cmd_settings:
      evm_version: london
      unlimited_contract_size: True
    # Workaround a brownie bug where it would just collect from mempool forever -.- (see Daniel)
    priority_fee: 2 gwei
  mainnet-fork:
    cmd_settings:
      evm_version: london
    # Workaround a brownie bug where it would just collect from mempool forever -.- (see Daniel)
    priority_fee: 2 gwei
