compiler:
  solc:
    version: 0.7.1
    optimizer:
      enabled: true
      runs: 200
    remappings:
      - "@balancer-labs=node_modules/@balancer-labs"
      - "@openzeppelin=node_modules/@openzeppelin"

networks:
  development:
    cmd_settings:
      evm_version: istanbul
      unlimited_contract_size: True
  mainnet-fork:
    cmd_settings:
      evm_version: istanbul
